#ifndef NATIVE_SCHEMA_REGISTRY_LIBNATIVESCHEMAREGISTRY_MOCK_H
#define NATIVE_SCHEMA_REGISTRY_LIBNATIVESCHEMAREGISTRY_MOCK_H

#include "graal_isolate.h"

enum MOCK_STATES {
    UNINITIALIZED = 8999,
    GRAAL_VM_INIT_SUCCESS = 9000,
    GRAAL_VM_INIT_FAIL = 9001,
    TEAR_DOWN_FAIL = 9003,
    ENCODE_FAILURE = 9004,
    DECODE_FAILURE = 9005,
    DECODE_SCHEMA_FAILURE = 9006,
    CAN_DECODE_FAILURE = 9007,
    CONFIG_INIT_SERIALIZER_FAIL = 9008,
    CONFIG_INIT_DESERIALIZER_FAIL = 9009,
    ATTACH_THREAD_FAIL = 9010,
    DETACH_THREAD_FAIL = 9011
};
void set_mock_state(int state);
void clear_mock_state(void);

#endif //NATIVE_SCHEMA_REGISTRY_LIBNATIVESCHEMAREGISTRY_MOCK_H