/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: /home/mrknox/workplace/knoxyGSRLibraryFork/native-schema-registry/c/src/swig/glue_schema_registry_serde.i */


extern
#ifdef __cplusplus
  "C"
#endif
  void cgo_panic__GsrSerDe_fa70d3d759b7424b(const char*);
static void _swig_gopanic(const char *p) {
  cgo_panic__GsrSerDe_fa70d3d759b7424b(p);
}



#define SWIG_VERSION 0x040301
#define SWIGGO
#define SWIGMODULE GsrSerDe
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >=201103L
# define SWIG_NULLPTR nullptr
#else
# define SWIG_NULLPTR NULL
#endif 

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 *
 * Note that SWIG expects __cplusplus to be defined to the appropriate C++ standard.
 * MSVC users are urged to check and examine the /Zc:__cplusplus compiler option.
 * See https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef ptrdiff_t intgo;
typedef size_t uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;



#define SWIG_exception(code, msg) _swig_gopanic(msg)


static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}




#include "read_only_byte_array.h"


#include "mutable_byte_array.h"


#include "glue_schema_registry_schema.h"


#include "glue_schema_registry_serializer.h"



#include "glue_schema_registry_deserializer.h"

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_GsrSerDe_fa70d3d759b7424b(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_GsrSerDe_fa70d3d759b7424b(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


struct read_only_byte_array *_wrap_new_read_only_byte_array_GsrSerDe_fa70d3d759b7424b(char *_swig_go_0, long long _swig_go_1, glue_schema_registry_error **_swig_go_2) {
  unsigned char *arg1 = (unsigned char *) 0 ;
  size_t arg2 ;
  glue_schema_registry_error **arg3 = (glue_schema_registry_error **) 0 ;
  struct read_only_byte_array *result = 0 ;
  struct read_only_byte_array *_swig_go_result;
  
  arg1 = *(unsigned char **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  arg3 = *(glue_schema_registry_error ***)&_swig_go_2; 
  
  result = (struct read_only_byte_array *)new_read_only_byte_array(arg1,arg2,arg3);
  *(struct read_only_byte_array **)&_swig_go_result = (struct read_only_byte_array *)result; 
  return _swig_go_result;
}


void _wrap_delete_read_only_byte_array_GsrSerDe_fa70d3d759b7424b(struct read_only_byte_array *_swig_go_0) {
  struct read_only_byte_array *arg1 = (struct read_only_byte_array *) 0 ;
  
  arg1 = *(struct read_only_byte_array **)&_swig_go_0; 
  
  delete_read_only_byte_array(arg1);
  
}


char *_wrap_read_only_byte_array_get_data_GsrSerDe_fa70d3d759b7424b(struct read_only_byte_array *_swig_go_0) {
  struct read_only_byte_array *arg1 = (struct read_only_byte_array *) 0 ;
  unsigned char *result = 0 ;
  char *_swig_go_result;
  
  arg1 = *(struct read_only_byte_array **)&_swig_go_0; 
  
  result = (unsigned char *)read_only_byte_array_get_data(arg1);
  *(unsigned char **)&_swig_go_result = (unsigned char *)result; 
  return _swig_go_result;
}


long long _wrap_read_only_byte_array_get_len_GsrSerDe_fa70d3d759b7424b(struct read_only_byte_array *_swig_go_0) {
  struct read_only_byte_array *arg1 = (struct read_only_byte_array *) 0 ;
  size_t result;
  long long _swig_go_result;
  
  arg1 = *(struct read_only_byte_array **)&_swig_go_0; 
  
  result = read_only_byte_array_get_len(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct mutable_byte_array *_wrap_new_mutable_byte_array_GsrSerDe_fa70d3d759b7424b(long long _swig_go_0, glue_schema_registry_error **_swig_go_1) {
  size_t arg1 ;
  glue_schema_registry_error **arg2 = (glue_schema_registry_error **) 0 ;
  struct mutable_byte_array *result = 0 ;
  struct mutable_byte_array *_swig_go_result;
  
  arg1 = (size_t)_swig_go_0; 
  arg2 = *(glue_schema_registry_error ***)&_swig_go_1; 
  
  result = (struct mutable_byte_array *)new_mutable_byte_array(arg1,arg2);
  *(struct mutable_byte_array **)&_swig_go_result = (struct mutable_byte_array *)result; 
  return _swig_go_result;
}


void _wrap_delete_mutable_byte_array_GsrSerDe_fa70d3d759b7424b(struct mutable_byte_array *_swig_go_0) {
  struct mutable_byte_array *arg1 = (struct mutable_byte_array *) 0 ;
  
  arg1 = *(struct mutable_byte_array **)&_swig_go_0; 
  
  delete_mutable_byte_array(arg1);
  
}


char *_wrap_mutable_byte_array_get_data_GsrSerDe_fa70d3d759b7424b(struct mutable_byte_array *_swig_go_0) {
  struct mutable_byte_array *arg1 = (struct mutable_byte_array *) 0 ;
  unsigned char *result = 0 ;
  char *_swig_go_result;
  
  arg1 = *(struct mutable_byte_array **)&_swig_go_0; 
  
  result = (unsigned char *)mutable_byte_array_get_data(arg1);
  *(unsigned char **)&_swig_go_result = (unsigned char *)result; 
  return _swig_go_result;
}


long long _wrap_mutable_byte_array_get_max_len_GsrSerDe_fa70d3d759b7424b(struct mutable_byte_array *_swig_go_0) {
  struct mutable_byte_array *arg1 = (struct mutable_byte_array *) 0 ;
  size_t result;
  long long _swig_go_result;
  
  arg1 = *(struct mutable_byte_array **)&_swig_go_0; 
  
  result = mutable_byte_array_get_max_len(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct glue_schema_registry_schema *_wrap_new_glue_schema_registry_schema_GsrSerDe_fa70d3d759b7424b(_gostring_ _swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2, _gostring_ _swig_go_3, glue_schema_registry_error **_swig_go_4) {
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  glue_schema_registry_error **arg5 = (glue_schema_registry_error **) 0 ;
  struct glue_schema_registry_schema *result = 0 ;
  struct glue_schema_registry_schema *_swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  arg4 = (char *)malloc(_swig_go_3.n + 1);
  memcpy(arg4, _swig_go_3.p, _swig_go_3.n);
  arg4[_swig_go_3.n] = '\0';
  
  arg5 = *(glue_schema_registry_error ***)&_swig_go_4; 
  
  result = (struct glue_schema_registry_schema *)new_glue_schema_registry_schema((char const *)arg1,(char const *)arg2,(char const *)arg3,(char const *)arg4,arg5);
  *(struct glue_schema_registry_schema **)&_swig_go_result = (struct glue_schema_registry_schema *)result; 
  free(arg1); 
  free(arg2); 
  free(arg3); 
  free(arg4); 
  return _swig_go_result;
}


void _wrap_delete_glue_schema_registry_schema_GsrSerDe_fa70d3d759b7424b(struct glue_schema_registry_schema *_swig_go_0) {
  struct glue_schema_registry_schema *arg1 = (struct glue_schema_registry_schema *) 0 ;
  
  arg1 = *(struct glue_schema_registry_schema **)&_swig_go_0; 
  
  delete_glue_schema_registry_schema(arg1);
  
}


_gostring_ _wrap_glue_schema_registry_schema_get_schema_name_GsrSerDe_fa70d3d759b7424b(struct glue_schema_registry_schema *_swig_go_0) {
  struct glue_schema_registry_schema *arg1 = (struct glue_schema_registry_schema *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(struct glue_schema_registry_schema **)&_swig_go_0; 
  
  result = (char *)glue_schema_registry_schema_get_schema_name(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


_gostring_ _wrap_glue_schema_registry_schema_get_schema_def_GsrSerDe_fa70d3d759b7424b(struct glue_schema_registry_schema *_swig_go_0) {
  struct glue_schema_registry_schema *arg1 = (struct glue_schema_registry_schema *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(struct glue_schema_registry_schema **)&_swig_go_0; 
  
  result = (char *)glue_schema_registry_schema_get_schema_def(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


_gostring_ _wrap_glue_schema_registry_schema_get_data_format_GsrSerDe_fa70d3d759b7424b(struct glue_schema_registry_schema *_swig_go_0) {
  struct glue_schema_registry_schema *arg1 = (struct glue_schema_registry_schema *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(struct glue_schema_registry_schema **)&_swig_go_0; 
  
  result = (char *)glue_schema_registry_schema_get_data_format(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


_gostring_ _wrap_glue_schema_registry_schema_get_additional_schema_info_GsrSerDe_fa70d3d759b7424b(struct glue_schema_registry_schema *_swig_go_0) {
  struct glue_schema_registry_schema *arg1 = (struct glue_schema_registry_schema *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(struct glue_schema_registry_schema **)&_swig_go_0; 
  
  result = (char *)glue_schema_registry_schema_get_additional_schema_info(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


struct glue_schema_registry_serializer *_wrap_new_glue_schema_registry_serializer_GsrSerDe_fa70d3d759b7424b(glue_schema_registry_error **_swig_go_0) {
  glue_schema_registry_error **arg1 = (glue_schema_registry_error **) 0 ;
  struct glue_schema_registry_serializer *result = 0 ;
  struct glue_schema_registry_serializer *_swig_go_result;
  
  arg1 = *(glue_schema_registry_error ***)&_swig_go_0; 
  
  result = (struct glue_schema_registry_serializer *)new_glue_schema_registry_serializer(arg1);
  *(struct glue_schema_registry_serializer **)&_swig_go_result = (struct glue_schema_registry_serializer *)result; 
  return _swig_go_result;
}


void _wrap_delete_glue_schema_registry_serializer_GsrSerDe_fa70d3d759b7424b(struct glue_schema_registry_serializer *_swig_go_0) {
  struct glue_schema_registry_serializer *arg1 = (struct glue_schema_registry_serializer *) 0 ;
  
  arg1 = *(struct glue_schema_registry_serializer **)&_swig_go_0; 
  
  delete_glue_schema_registry_serializer(arg1);
  
}


struct mutable_byte_array *_wrap_glue_schema_registry_serializer_encode_GsrSerDe_fa70d3d759b7424b(struct glue_schema_registry_serializer *_swig_go_0, struct read_only_byte_array *_swig_go_1, _gostring_ _swig_go_2, struct glue_schema_registry_schema *_swig_go_3, glue_schema_registry_error **_swig_go_4) {
  struct glue_schema_registry_serializer *arg1 = (struct glue_schema_registry_serializer *) 0 ;
  read_only_byte_array *arg2 = (read_only_byte_array *) 0 ;
  char *arg3 = (char *) 0 ;
  glue_schema_registry_schema *arg4 = (glue_schema_registry_schema *) 0 ;
  glue_schema_registry_error **arg5 = (glue_schema_registry_error **) 0 ;
  mutable_byte_array *result = 0 ;
  struct mutable_byte_array *_swig_go_result;
  
  arg1 = *(struct glue_schema_registry_serializer **)&_swig_go_0; 
  arg2 = *(read_only_byte_array **)&_swig_go_1; 
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  arg4 = *(glue_schema_registry_schema **)&_swig_go_3; 
  arg5 = *(glue_schema_registry_error ***)&_swig_go_4; 
  
  {
    //Initialize the error pointer holder argument. It is expected that the target language caller passes null here.
    arg5 = new_glue_schema_registry_error_holder();
    
    //Execute the method
    result = (mutable_byte_array *)glue_schema_registry_serializer_encode(arg1,arg2,(char const *)arg3,arg4,arg5);
    
    //Obtain the error pointer post execution.
    glue_schema_registry_error *err = *arg5;
    
    //if the error is set to NULL, no exception occurred.
    if (err == NULL) {
      //Release the error pointer holder.
      delete_glue_schema_registry_error_holder(arg5);
    } else {
      //Throw the exception
      if (err->msg == NULL || strlen(err->msg) == 0) {
        //Make sure memory is released before throwing exception.
        delete_glue_schema_registry_error_holder(arg5);
        
        SWIG_exception(SWIG_RuntimeError, "Unknown exception occurred.");
      } else {
        //Temporarily copy the error_msg to stack before releasing the error pointers.
        char msg[MAX_ERROR_MSG_LEN];
        glue_schema_registry_error_get_msg(err, msg, sizeof msg);
        
        int err_code = err->code;
        
        //Make sure memory is released before throwing exception.
        delete_glue_schema_registry_error_holder(arg5);
        
        if (err_code == ERR_CODE_NULL_PARAMETERS || err_code == ERR_CODE_INVALID_PARAMETERS) {
          SWIG_exception(SWIG_ValueError, msg);
        } else {
          SWIG_exception(SWIG_RuntimeError, msg);
        }
      }
    }
  }
  *(mutable_byte_array **)&_swig_go_result = (mutable_byte_array *)result; 
  free(arg3); 
  return _swig_go_result;
}


struct glue_schema_registry_deserializer *_wrap_new_glue_schema_registry_deserializer_GsrSerDe_fa70d3d759b7424b(glue_schema_registry_error **_swig_go_0) {
  glue_schema_registry_error **arg1 = (glue_schema_registry_error **) 0 ;
  struct glue_schema_registry_deserializer *result = 0 ;
  struct glue_schema_registry_deserializer *_swig_go_result;
  
  arg1 = *(glue_schema_registry_error ***)&_swig_go_0; 
  
  result = (struct glue_schema_registry_deserializer *)new_glue_schema_registry_deserializer(arg1);
  *(struct glue_schema_registry_deserializer **)&_swig_go_result = (struct glue_schema_registry_deserializer *)result; 
  return _swig_go_result;
}


void _wrap_delete_glue_schema_registry_deserializer_GsrSerDe_fa70d3d759b7424b(struct glue_schema_registry_deserializer *_swig_go_0) {
  struct glue_schema_registry_deserializer *arg1 = (struct glue_schema_registry_deserializer *) 0 ;
  
  arg1 = *(struct glue_schema_registry_deserializer **)&_swig_go_0; 
  
  delete_glue_schema_registry_deserializer(arg1);
  
}


struct mutable_byte_array *_wrap_glue_schema_registry_deserializer_decode_GsrSerDe_fa70d3d759b7424b(struct glue_schema_registry_deserializer *_swig_go_0, struct read_only_byte_array *_swig_go_1, glue_schema_registry_error **_swig_go_2) {
  struct glue_schema_registry_deserializer *arg1 = (struct glue_schema_registry_deserializer *) 0 ;
  read_only_byte_array *arg2 = (read_only_byte_array *) 0 ;
  glue_schema_registry_error **arg3 = (glue_schema_registry_error **) 0 ;
  mutable_byte_array *result = 0 ;
  struct mutable_byte_array *_swig_go_result;
  
  arg1 = *(struct glue_schema_registry_deserializer **)&_swig_go_0; 
  arg2 = *(read_only_byte_array **)&_swig_go_1; 
  arg3 = *(glue_schema_registry_error ***)&_swig_go_2; 
  
  {
    //Initialize the error pointer holder argument. It is expected that the target language caller passes null here.
    arg3 = new_glue_schema_registry_error_holder();
    
    //Execute the method
    result = (mutable_byte_array *)glue_schema_registry_deserializer_decode(arg1,arg2,arg3);
    
    //Obtain the error pointer post execution.
    glue_schema_registry_error *err = *arg3;
    
    //if the error is set to NULL, no exception occurred.
    if (err == NULL) {
      //Release the error pointer holder.
      delete_glue_schema_registry_error_holder(arg3);
    } else {
      //Throw the exception
      if (err->msg == NULL || strlen(err->msg) == 0) {
        //Make sure memory is released before throwing exception.
        delete_glue_schema_registry_error_holder(arg3);
        
        SWIG_exception(SWIG_RuntimeError, "Unknown exception occurred.");
      } else {
        //Temporarily copy the error_msg to stack before releasing the error pointers.
        char msg[MAX_ERROR_MSG_LEN];
        glue_schema_registry_error_get_msg(err, msg, sizeof msg);
        
        int err_code = err->code;
        
        //Make sure memory is released before throwing exception.
        delete_glue_schema_registry_error_holder(arg3);
        
        if (err_code == ERR_CODE_NULL_PARAMETERS || err_code == ERR_CODE_INVALID_PARAMETERS) {
          SWIG_exception(SWIG_ValueError, msg);
        } else {
          SWIG_exception(SWIG_RuntimeError, msg);
        }
      }
    }
  }
  *(mutable_byte_array **)&_swig_go_result = (mutable_byte_array *)result; 
  return _swig_go_result;
}


bool _wrap_glue_schema_registry_deserializer_can_decode_GsrSerDe_fa70d3d759b7424b(struct glue_schema_registry_deserializer *_swig_go_0, struct read_only_byte_array *_swig_go_1, glue_schema_registry_error **_swig_go_2) {
  struct glue_schema_registry_deserializer *arg1 = (struct glue_schema_registry_deserializer *) 0 ;
  read_only_byte_array *arg2 = (read_only_byte_array *) 0 ;
  glue_schema_registry_error **arg3 = (glue_schema_registry_error **) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(struct glue_schema_registry_deserializer **)&_swig_go_0; 
  arg2 = *(read_only_byte_array **)&_swig_go_1; 
  arg3 = *(glue_schema_registry_error ***)&_swig_go_2; 
  
  {
    //Initialize the error pointer holder argument. It is expected that the target language caller passes null here.
    arg3 = new_glue_schema_registry_error_holder();
    
    //Execute the method
    result = (bool)glue_schema_registry_deserializer_can_decode(arg1,arg2,arg3);
    
    //Obtain the error pointer post execution.
    glue_schema_registry_error *err = *arg3;
    
    //if the error is set to NULL, no exception occurred.
    if (err == NULL) {
      //Release the error pointer holder.
      delete_glue_schema_registry_error_holder(arg3);
    } else {
      //Throw the exception
      if (err->msg == NULL || strlen(err->msg) == 0) {
        //Make sure memory is released before throwing exception.
        delete_glue_schema_registry_error_holder(arg3);
        
        SWIG_exception(SWIG_RuntimeError, "Unknown exception occurred.");
      } else {
        //Temporarily copy the error_msg to stack before releasing the error pointers.
        char msg[MAX_ERROR_MSG_LEN];
        glue_schema_registry_error_get_msg(err, msg, sizeof msg);
        
        int err_code = err->code;
        
        //Make sure memory is released before throwing exception.
        delete_glue_schema_registry_error_holder(arg3);
        
        if (err_code == ERR_CODE_NULL_PARAMETERS || err_code == ERR_CODE_INVALID_PARAMETERS) {
          SWIG_exception(SWIG_ValueError, msg);
        } else {
          SWIG_exception(SWIG_RuntimeError, msg);
        }
      }
    }
  }
  _swig_go_result = result; 
  return _swig_go_result;
}


struct glue_schema_registry_schema *_wrap_glue_schema_registry_deserializer_decode_schema_GsrSerDe_fa70d3d759b7424b(struct glue_schema_registry_deserializer *_swig_go_0, struct read_only_byte_array *_swig_go_1, glue_schema_registry_error **_swig_go_2) {
  struct glue_schema_registry_deserializer *arg1 = (struct glue_schema_registry_deserializer *) 0 ;
  read_only_byte_array *arg2 = (read_only_byte_array *) 0 ;
  glue_schema_registry_error **arg3 = (glue_schema_registry_error **) 0 ;
  glue_schema_registry_schema *result = 0 ;
  struct glue_schema_registry_schema *_swig_go_result;
  
  arg1 = *(struct glue_schema_registry_deserializer **)&_swig_go_0; 
  arg2 = *(read_only_byte_array **)&_swig_go_1; 
  arg3 = *(glue_schema_registry_error ***)&_swig_go_2; 
  
  {
    //Initialize the error pointer holder argument. It is expected that the target language caller passes null here.
    arg3 = new_glue_schema_registry_error_holder();
    
    //Execute the method
    result = (glue_schema_registry_schema *)glue_schema_registry_deserializer_decode_schema(arg1,arg2,arg3);
    
    //Obtain the error pointer post execution.
    glue_schema_registry_error *err = *arg3;
    
    //if the error is set to NULL, no exception occurred.
    if (err == NULL) {
      //Release the error pointer holder.
      delete_glue_schema_registry_error_holder(arg3);
    } else {
      //Throw the exception
      if (err->msg == NULL || strlen(err->msg) == 0) {
        //Make sure memory is released before throwing exception.
        delete_glue_schema_registry_error_holder(arg3);
        
        SWIG_exception(SWIG_RuntimeError, "Unknown exception occurred.");
      } else {
        //Temporarily copy the error_msg to stack before releasing the error pointers.
        char msg[MAX_ERROR_MSG_LEN];
        glue_schema_registry_error_get_msg(err, msg, sizeof msg);
        
        int err_code = err->code;
        
        //Make sure memory is released before throwing exception.
        delete_glue_schema_registry_error_holder(arg3);
        
        if (err_code == ERR_CODE_NULL_PARAMETERS || err_code == ERR_CODE_INVALID_PARAMETERS) {
          SWIG_exception(SWIG_ValueError, msg);
        } else {
          SWIG_exception(SWIG_RuntimeError, msg);
        }
      }
    }
  }
  *(glue_schema_registry_schema **)&_swig_go_result = (glue_schema_registry_schema *)result; 
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

