services:
  zookeeper:
    image: 'public.ecr.aws/bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'public.ecr.aws/bitnami/kafka:3.5'
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    container_name: local_kafka_dockerized
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes

  golang-tests:
    build:
      context: ../..
      dockerfile: golang/integration-tests/Dockerfile.dockerized-tests
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - COVERAGE=${COVERAGE:-false}
    volumes:
      - ../build:/app/native-schema-registry/golang/build
      - ./docker-logs.txt:/app/native-schema-registry/golang/integration-tests/docker-logs.txt
      - ~/.aws:/root/.aws:ro
    networks:
      - default
