version: '3.8'

services:
  zookeeper:
    image: 'public.ecr.aws/bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'public.ecr.aws/bitnami/kafka:3.5'
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    container_name: local_kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
  demo-csharp-protobuf:
    image: mcr.microsoft.com/dotnet/sdk:8.0-noble
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - AWS_REGION=${AWS_REGION:-us-east-1}
    volumes:
      - ~/.aws:/root/.aws:ro
      - .:/workplace/demos/csharp
      - ../../csharp:/workplace/csharp
    working_dir: /workplace/demos/csharp
    command: ["./run-demo.sh"]