// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: test_message.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Simple test message for integration tests
type TestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage) Reset() {
	*x = TestMessage{}
	mi := &file_test_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage) ProtoMessage() {}

func (x *TestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage.ProtoReflect.Descriptor instead.
func (*TestMessage) Descriptor() ([]byte, []int) {
	return file_test_message_proto_rawDescGZIP(), []int{0}
}

func (x *TestMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestMessage) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *TestMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TestMessage) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_test_message_proto protoreflect.FileDescriptor

const file_test_message_proto_rawDesc = "" +
	"\n" +
	"\x12test_message.proto\x12\x04test\"m\n" +
	"\vTestMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tagsBdZbgithub.com/awslabs/aws-glue-schema-registry/native-schema-registry/golang/integration-tests/testpbb\x06proto3"

var (
	file_test_message_proto_rawDescOnce sync.Once
	file_test_message_proto_rawDescData []byte
)

func file_test_message_proto_rawDescGZIP() []byte {
	file_test_message_proto_rawDescOnce.Do(func() {
		file_test_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_message_proto_rawDesc), len(file_test_message_proto_rawDesc)))
	})
	return file_test_message_proto_rawDescData
}

var file_test_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_test_message_proto_goTypes = []any{
	(*TestMessage)(nil), // 0: test.TestMessage
}
var file_test_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_message_proto_init() }
func file_test_message_proto_init() {
	if File_test_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_message_proto_rawDesc), len(file_test_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_message_proto_goTypes,
		DependencyIndexes: file_test_message_proto_depIdxs,
		MessageInfos:      file_test_message_proto_msgTypes,
	}.Build()
	File_test_message_proto = out.File
	file_test_message_proto_goTypes = nil
	file_test_message_proto_depIdxs = nil
}
