name: MavenCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    branches: [ master ]
    types: [ created ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    continue-on-error: false
    timeout-minutes: 60
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        java-version: ['8', '11', '17']

    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      with:
        persist-credentials: false

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4.9.1
      with:
        distribution: 'corretto'
        java-version: ${{ matrix.java-version }}

    - name: Cache Maven packages
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Clean, build and install
      run: mvn --file pom.xml clean install

    - name: Build package
      run: mvn -B package --file pom.xml
